### ISSUE TITLE
New design for homepage

### ISSUE THREAD

**Issue by manishsaraan** [manishsaraan/looking-for-maintainers#2]
New design for homepage. Current one does not match with other pages.

**Comment by RocktimSaikia** [comment]
Hey there ! Can i work on the basic home page design of this project for now? If i can then please let me know about the tech stack used on this repo .

**Comment by manishsaraan** [comment]
Hi Rocktim,
I am glad to hear that you are interested to contribute in this project.
You are more than welcome to contribute. I need help with design.
This project is written in react and nodejs.
If you are not familiar with these then you can work with HTML.
Let me know if you’re have any question

**Comment by RocktimSaikia** [comment]
okey .I am pretty familiar with node and have decent amount of knowledge on react. So what i wanna ask is that the main motive of this project is to help project owners look for maintainers right ? So how is this base process gonna work , i mean like are you gonna get every one's github details when they authenticate to github with this app or you're gonna have a functionality in your web page where people can just submit their github info  so that others know that they are available to work as maintainers ?

**Comment by manishsaraan** [comment]
For now i am using just the repo owner to authenticate and select repo to publish on site. Then the published repo will be listed on explore page. Here anyone can view all the repos who's owners are looking for maintainers. I am using explore page only for viewing all repos and users can sort bases on languages, no of starts etc.
I still need to work on maintainer and repo owner communication, so that repo owner can know that potential maintainer is interested in contribution. For not there is only way to create issue on github like we are doing here.
I am also thinking to send weekly newsletter with new repo published.
What are your thoughts about this flow ?

**Comment by RocktimSaikia** [comment]
okey that sounds really interesting.I guess you have to work on the server side pretty soon so that the front end can be designed based on the backend.okey for now i wanna work on the base home page design just to get started with the flow of the process.So can you give me some ideas and requirements on how the page should look for now? may be diagram or flowchart would be helpful if you have time.You can email me about the your design vision for the page at  srocktim61@gmail.com .so that i can work on it asap.

**Comment by RocktimSaikia** [comment]
i just forked the repo and saw that you already worked on the base design.This is great.Btw i think i need to have mongodb installed and running locally in order to run this project in a local machine , right ?

**Comment by manishsaraan** [comment]
Yes. I am almost done with functionality. Only pending thing is homepage
design. You can set   Your credentials in .env file. Main working branch
react-frontend.
Pages
/explore explore page
/profile profile page

**Comment by RocktimSaikia** [comment]
i'm getting the the design base but i'm kinda stuck on running the project locally.As its kinda hard to jump into a project that is more of  database program.Plus there is no contribution guide for this .Can you be more specific about the required steps need to be taken in simple means to get started with the local development environment for this project.Which can be helpful for others too who is looking forward to work on this project ?

**Comment by manishsaraan** [comment]
I am at office right now. I will share everything tomorrow.
Till you can check the live
Lookingformaintainers.com
I am working alone that’s why I didn’t put any info

**Comment by RocktimSaikia** [comment]
Ok. Looking forward for the contribution guide.And btw your current site "Lookingformaintainers.com" keeps getting stuck on "Loggin to github....." message .

**Comment by manishsaraan** [comment]
Hmm. I need to update the api code for that working

**Comment by manishsaraan** [comment]
Hi Rocktim,
I have fixed the site not working issue. For now i am using ip for backend
api baseurl because my sub domain redirection is not working. So you need
to manually allow certificates to make it work.
Visit https://134.209.55.236:3001 to accept certificates.

How to run project on local
Current working branch is *react-frontend. *I also included the steps in
readme as well.
Run server
Install node modules with npm install
Edit .env file and add your credentials like github id and secret. I have
included my .env file in attachment.
Run project with node index.js

Run client
Go to client directory.
Install node modules with npm install
Edit src/config/index.js and add GitHub client id and secret and api
endpoint which should be https://localhost:3001/api.
Run with npm start.

You can work on homepage where we will ask users to login with GitHub and
subscribe to emails.
Saving user emails is done on server side but you can create a form to save
user's first name, last name and email id.

If you have any question, let me know.

Regards,
Manish

**Comment by RocktimSaikia** [comment]
@manishsaraan great 🙌 i will take a look at the project with the specified info that you just provided. Currently lil busy.Will work on this tonight 😇 .

**Comment by RocktimSaikia** [comment]
@manishsaraan hi i think you still have not pushed your new changes like readme and env file to this repo. Cause your readme file is still empty. And your last commit was in early january

**Comment by manishsaraan** [comment]
Latest changes are in react-frontend branch
